# Generated by Django 5.0.3 on 2024-03-05 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SubscriptionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sub_type",
                    models.CharField(
                        choices=[
                            ("SPLIT", "Split"),
                            ("PERSONAL", "Personal"),
                            ("GROUP", "Group"),
                            ("KIDS", "Kids"),
                            ("ONETIME", "One time"),
                        ],
                        default="ONETIME",
                        max_length=63,
                    ),
                ),
                (
                    "number_of_workouts",
                    models.IntegerField(
                        choices=[(1, 1), (4, 4), (8, 8), (12, 12)], default=1
                    ),
                ),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Trainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=63)),
                ("surname", models.CharField(max_length=63)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="TrainingType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "training_type",
                    models.CharField(
                        choices=[
                            ("Stretching", "Stretching"),
                            ("Functional", "Functional"),
                            ("Kids", "Kids"),
                            ("Bare", "Bare"),
                            ("Stretching Pro", "Stretching Pro"),
                            ("TRX", "TRX"),
                            ("Functional+Stretching", "Functional+Stretching"),
                        ],
                        default="Stretching",
                        max_length=63,
                    ),
                ),
                ("duration", models.IntegerField()),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brought_at", models.DateTimeField(auto_now_add=True)),
                ("activated_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_valid", models.BooleanField(default=True)),
                ("visit_count", models.IntegerField(default=0)),
                (
                    "subscription_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="gym_api.subscriptiontype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                            ("Sunday", "Sunday"),
                        ],
                        default="Monday",
                        max_length=63,
                    ),
                ),
                ("time", models.TimeField()),
                ("price", models.IntegerField()),
                ("max_visitors", models.IntegerField(default=10)),
                (
                    "trainer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedule",
                        to="gym_api.trainer",
                    ),
                ),
                (
                    "training_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule",
                        to="gym_api.trainingtype",
                    ),
                ),
            ],
            options={
                "ordering": ["time"],
            },
        ),
        migrations.CreateModel(
            name="Signup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signups",
                        to="gym_api.training",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="trainer",
            name="training_types",
            field=models.ManyToManyField(
                related_name="trainers", to="gym_api.trainingtype"
            ),
        ),
    ]
