# Generated by Django 5.0.3 on 2024-03-05 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gym_api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="visitor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="gym_api.visitor",
            ),
        ),
        migrations.AddField(
            model_name="signup",
            name="visitor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="signups",
                to="gym_api.visitor",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="training",
            unique_together={("day_of_week", "time", "training_type")},
        ),
        migrations.AlterUniqueTogether(
            name="signup",
            unique_together={("date", "training", "visitor")},
        ),
    ]
