# Generated by Django 5.0.3 on 2024-03-06 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_api", "0004_alter_training_trainer_alter_visitor_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="training",
            name="trainer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schedule",
                to="gym_api.trainer",
            ),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
