# Generated by Django 5.0.3 on 2024-03-06 11:48

import gym_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_api", "0006_discount_subscriptiontype_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainer",
            name="image",
        ),
        migrations.AddField(
            model_name="trainer",
            name="trainer_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=gym_api.models.image_file_path
            ),
        ),
        migrations.AddField(
            model_name="visitor",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to=gym_api.models.image_file_path
            ),
        ),
    ]
