# Generated by Django 5.0.3 on 2024-03-06 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_api", "0007_remove_trainer_image_trainer_trainer_photo_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptiontype",
            options={"ordering": ["sub_type"]},
        ),
        migrations.AddField(
            model_name="subscription",
            name="discount",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscriptions",
                to="gym_api.discount",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subscriptiontype",
            unique_together={("sub_type", "number_of_workouts")},
        ),
    ]
