# Generated by Django 5.0.3 on 2024-03-07 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "gym_api",
            "0008_alter_subscriptiontype_options_subscription_discount_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="trainingtype",
            old_name="training_type",
            new_name="name",
        ),
    ]
