# Generated by Django 5.0.3 on 2024-03-07 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_api", "0009_rename_training_type_trainingtype_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="training",
            options={"ordering": ["date", "schedule__time"]},
        ),
        migrations.AlterUniqueTogether(
            name="signup",
            unique_together={("training", "visitor")},
        ),
        migrations.AddField(
            model_name="training",
            name="date",
            field=models.DateField(default="2024-03-07"),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("Понеділок", "Понеділок"),
                            ("Вівторок", "Вівторок"),
                            ("Середа", "Середа"),
                            ("Четвер", "Четвер"),
                            ("П'ятниця", "П'ятниця"),
                            ("Субота", "Субота"),
                            ("Неділя", "Неділя"),
                        ],
                        default="Понеділок",
                        max_length=63,
                    ),
                ),
                ("time", models.TimeField()),
                ("price", models.IntegerField()),
                ("max_visitors", models.IntegerField(default=10)),
                (
                    "trainer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedule",
                        to="gym_api.trainer",
                    ),
                ),
                (
                    "training_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule",
                        to="gym_api.trainingtype",
                    ),
                ),
            ],
            options={
                "ordering": ["day_of_week", "time"],
                "unique_together": {("day_of_week", "time", "training_type")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="training",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="training",
            name="schedule",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trainings",
                to="gym_api.schedule",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="training",
            unique_together={("date", "schedule")},
        ),
        migrations.RemoveField(
            model_name="signup",
            name="date",
        ),
        migrations.RemoveField(
            model_name="training",
            name="day_of_week",
        ),
        migrations.RemoveField(
            model_name="training",
            name="max_visitors",
        ),
        migrations.RemoveField(
            model_name="training",
            name="price",
        ),
        migrations.RemoveField(
            model_name="training",
            name="time",
        ),
        migrations.RemoveField(
            model_name="training",
            name="trainer",
        ),
        migrations.RemoveField(
            model_name="training",
            name="training_type",
        ),
    ]
