# Generated by Django 5.0.3 on 2024-03-07 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gym_api",
            "0010_alter_training_options_alter_signup_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="training",
            name="schedule",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trainings",
                to="gym_api.schedule",
            ),
        ),
    ]
