# Generated by Django 5.0.3 on 2024-03-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gym_api", "0012_alter_training_schedule"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="training",
            options={"ordering": ["date", "training__time"]},
        ),
        migrations.RenameField(
            model_name="training",
            old_name="schedule",
            new_name="training",
        ),
        migrations.AlterUniqueTogether(
            name="training",
            unique_together={("date", "training")},
        ),
    ]
