# Generated by Django 5.0.3 on 2024-03-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="Visistor", max_length=63),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="surname",
            field=models.CharField(default="Surname", max_length=63),
            preserve_default=False,
        ),
    ]
