# Generated by Django 5.0.3 on 2024-03-06 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_name_user_surname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="surname",
        ),
    ]
